name: ci

on:
  push:
    branches:
      - 'main'
env:
  IMAGE_NAME: app
  
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest, ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - 
        name: Dispatch Event
        uses: guilouro/multiple-repositories-dispatch@v1
        with:
          repo_token: ${{ secrets.PAT }}
          event_type: event_name
          repositories: safernandez666/GitHubGitOps
          client_payload: '{"github": ${{ toJson(github) }}}'